### ISSUE TITLE
Issues with the plugin

### ISSUE THREAD

**Issue by Boboer324** [jerzean/UltimateSurvivalGames#2]
Plugins:
EssentialsX-2.17.2.0
InvseePlugin
Multiverse-Core-4.1.0
OwnGarden
UltimateSurvivalGames
worldedit-bukkit-7.0.1
Spigot 1.16.1

My issues was that i had to restart the server everytime we played a round bc the the sgin just said reset forever, the second issue i had that we couldnt break leaves/any block on the map although i added it in the config.

**Comment by jerzean** [comment]
@Boboer324  this plugin requires Async World edit or Fast async world edit,  Regular worldedit will crash/fail due to the arena size being so large

ill look into the other issue
