### ISSUE TITLE
Arena wont reset after game

### ISSUE THREAD

**Issue by TheHappyHopper** [jerzean/UltimateSurvivalGames#5]
I've been finding that the arena takes a rather significant chunk of time to reset after each game, it will say "this game is not running" 10 to 20 minutes after the previous game has ended, the longest it's taken is 45 minutes.

**Comment by jerzean** [comment]
Reset time depends on how the server is running  Async is meant to eliminate lag from worldedit if the server is overloaded it'll take a long time to reset.  I suggest setting up a few of the same arenas
