### ISSUE TITLE
Game doesn't end after last tribute dies

### ISSUE THREAD

**Issue by TheHappyHopper** [jerzean/UltimateSurvivalGames#6]
The game seems to be having trouble figuring out when to end when there's more than one arena attached to the lobby, it causes anyone trying to join the lobby, to join the arena in spectator mode and forces us to do a reload of the lobby to reset it.

**Comment by jerzean** [comment]
im currently setting up a testing server  seeing as i dont have enough people to test this/be able to reproduce this error/bug

**Comment by TheHappyHopper** [comment]
Would you like my help?
